ToDoro/ToDoro_project/urls.py
from django.contrib import admin
from django.urls import path

from ToDoro_app import views

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", views.base, name='base'),

    path("delete_item/<int:item_id>", views.delete_item, name="delete_item"),
    path("delete_list/<int:title_id>", views.delete_list, name="delete_list"),
    
    path("edit_item/<int:item_id>", views.edit_item, name="edit_item"),
    path("edit_title/<int:title_id>", views.edit_title, name="edit_title"),
    
    path("done/<int:item_id>", views.done, name="done"),
    path("incomplete/<int:item_id>", views.incomplete, name="incomplete"),
]

ToDoro/ToDoro_app/models.py
from django.db import models


class TodoList(models.Model):
	title = models.CharField(max_length=150)

	def __str__(self):
		return self.title


class TodoItem(models.Model):
	item = models.CharField(max_length=200)
	todolist = models.ForeignKey('TodoList', on_delete=models.CASCADE)
	completed = models.BooleanField(default=False)

	def __str__(self):
		return self.item 

ToDoro/ToDoro_app/forms.py
from django import forms  
from .models import TodoItem, TodoList


class TodoItemForm(forms.ModelForm):
	class Meta:
		model = TodoItem
		fields = '__all__'


class TodoListForm(forms.ModelForm):
	class Meta:
		model = TodoList
		fields = ('title',)

		

ToDoro/ToDoro_app/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponseRedirect
from django.views.decorators.csrf import csrf_exempt
from django.contrib import messages

from .models import TodoList, TodoItem
from .forms import TodoItemForm, TodoListForm


@csrf_exempt
def base(request):
	# POST method to create the title of the ToDoro List:
	if request.method == "POST":
		form_list = TodoListForm(request.POST)
		if form_list.is_valid():
			form_list.save()
			messages.success(request, ('List title successfully created!'))
			return HttpResponseRedirect('/')

	else:
		form_list = TodoListForm()

	# POST method to add items to a ToDoro List:
	if request.method == "POST":
		form_item = TodoItemForm(request.POST)
		if form_item.is_valid():
			form_item.save()
			messages.success(request, ('New list item added!'))
			return HttpResponseRedirect('/')
			
	else:
		form_item = TodoItemForm()

	# grap all TodoLists (titles) from database:
	titles = TodoList.objects.all()

	return render(request, 'home.html', 
		{
		'form_list': form_list, 
		'form_item': form_item,
		'titles': titles
		})


# delete the list:
def delete_list(request, title_id):
	# get the titel of todo list:
	todolist = TodoList.objects.get(id=title_id)
	todolist.delete()
	messages.success(request, ('List has been deleted!'))
	return HttpResponseRedirect('/')


# delete an item of a list:
def delete_item(request, item_id):
	item = TodoItem.objects.get(id=item_id)
	item.delete()
	messages.success(request, ('List item has been deleted!'))
	return HttpResponseRedirect('/')


# edit the title:
@csrf_exempt
def edit_title(request, title_id):
	title = TodoList.objects.get(id=title_id)

	if request.method == "POST":
		form = TodoListForm(request.POST, instance=title)
		if form.is_valid():
			form.save()
			messages.success(request, ('List title successfully edited!'))
			return redirect('/')

	else:
		form = TodoListForm(instance=title)

	return render(request, 'edit_title.html', {'form': form})


# edit the item:
@csrf_exempt
def edit_item(request, item_id):
	item = TodoItem.objects.get(id=item_id)
	
	if request.method == "POST":
		form = TodoItemForm(request.POST, instance=item)
		if form.is_valid():
			form.save()
			messages.success(request, ('List item successfully edited!'))
			return redirect('/')

	else:
		form = TodoItemForm(instance=item)

	return render(request, 'edit_item.html', {'form': form})


def done(request, item_id):
	# search for items which are completed (done):
	done = TodoItem.objects.get(id=item_id)
	done.completed = False
	done.save()
	return HttpResponseRedirect('/')


def incomplete(request, item_id):
	# search for items which are incomplete:
	incomplete = TodoItem.objects.get(id=item_id)
	print(incomplete)
	print('1st bool: ', incomplete.completed)
	incomplete.completed = True
	print('bool: ', incomplete.completed)
	incomplete.save()
	return HttpResponseRedirect('/')




		

ToDoro/ToDoro_app/templates/base.html
<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">

    <title>ToDoro App</title>

    <!-- fontawesom link --> 
    <script defer src="https://use.fontawesome.com/releases/v5.3.1/js/all.js"></script>
    
    <!-- bootstrap cdn -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">

</head>
<body>

  <!-- Navbar -->
    <nav class="navbar navbar-expand-lg navbar-light sticky-top" style="background-color: #e3f2fd;">
      <a href="/" class="navbar-brand">ToDoro Application</a>
    </nav>
  <!-- End of Navbar -->

  {% block content %}

  {% endblock %}
  
  <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
  <script src="https://cdn.jsdelivr.net/npm/popper.js@1.12.9/dist/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>


</body>
</html>

ToDoro/ToDoro_app/templates/edit_item.html
{% extends 'base.html' %}

{% block content %}

  <!-- Edit ToDoro Item Component -->
  <div class="container">
    <div class="row">
      <div class="col-md-7">
        <div class="card border-dark bg-light my-3" >
          <div class="card-header bg-transparent ">
            <form method="POST">
            {% csrf_token %}
              {{ form.as_p }}      
    
              <input class="btn btn-success btn-sm" type="submit" value="Edit Item">
          	</form>
          </div>
        </div>
      </div>
    </div>
  </div> 
  <!-- End of Edit ToDoro Item Component -->

{% endblock %}

ToDoro/ToDoro_app/templates/edit_title.html
{% extends 'base.html' %}

{% block content %}

  <!-- Edit ToDoro Item Component -->
  <div class="container">
    <div class="row">
      <div class="col-md-7">
        <div class="card border-dark bg-light my-3" >
          <div class="card-header bg-transparent ">
            <form method="POST">
            {% csrf_token %}
              {{ form.as_p }}      
    
              <input class="btn btn-success btn-sm" type="submit" value="Edit Item">
            </form>
          </div>
        </div>
      </div>
    </div>
  </div> 
  <!-- End of Edit ToDoro Item Component -->

{% endblock %}

ToDoro/ToDoro_app/templates/home.html
{% extends 'base.html' %}

{% block content %}
  
  <!-- Messages Component -->
  <div class="container mt-2">
  {% if messages %}
    {% for message in messages %}
      <article class="alert alert-success" role="alert">
        <div class="message-body">
            {{ message }}
        </div>
      </article>
    {% endfor %}
  {% endif %}
  </div>
    <!-- End of Messages Component -->

  <!-- Create new ToDoro List Component -->
  <div class="container mt-2">
    <div class="row">
      <div class="col-md-6">
        <div class="card border-dark bg-light my-2" >
          <div class="card-header bg-transparent ">
            <h5>Create a new ToDoro list: </h5>
            <form method="POST">
              {% csrf_token %}
              {{ form_list.as_p }}
              <input class="btn btn-primary btn-sm" type="submit" value="Add Title">
            </form>
          </div>
        </div>
      </div>
            
      <div class="col-md-6">
        <div class="card border-dark bg-light my-2" >
          <div class="card-header bg-transparent ">
            <h5> Add item to ToDoro list: </h5>
            <form method="POST">
              {% csrf_token %}
                {{ form_item.as_p }}
              <input class="btn btn-primary btn-sm" type="submit" value="Add Item">
            </form>
          </div>
        </div>
      </div>
    </div>
  </div>
  <!-- End of Create new ToDoro List Component -->

  <hr>

  <!-- Display ToDoro List Component -->
  <div class="container">
    <div class="row">
      {% for title in titles %}
      <div class="col-md-6">
        <div class="card border-dark bg-light my-2" >
          <div class="card-header bg-transparent ">
              <a href="{% url 'edit_title' title.id %}" class="mx-3"><i class="far fa-edit fa-sm"></i></a>
              <strong>{{ title }}</strong>
          </div>

          <div class="card-body">
            <div class="card">
              <table class="table table-striped">
                <tbody>
                {% for item in title.todoitem_set.all %}
                  <tr>
                    <td>
                        <a href="{% url 'edit_item' item.id %}"><i class="far fa-edit fa-sm"></i></a> 
                        <a href="{% url 'delete_item' item.id %}"><i class="far fa-trash-alt fa-sm"></i></a>
                    </td>
                    
                    <td>
                      {% if item.completed == True %}
                        <span style="text-decoration: line-through;">{{ item }}</span>
                      {% else %}
                        {{ item }}
                      {% endif %}
                    </td>

                    <td>
                      {% if item.completed == True %}
                        <a href="{% url 'done' item.id %}"><i class="far fa-check-circle fa-sm"></i></a>
                      {% else %}
                        <a href="{% url 'incomplete' item.id%}"><i class="far fa-circle fa-sm"></i></a>
                      {% endif %}
                    </td>

                  </tr>
                {% endfor %}
                </tbody>
              </table>
            </div>

            <div class="mt-3">
              <a href="{% url 'delete_list' title.id %}">
                <input class="btn btn-danger btn-sm" type="submit" value="Delete List">
              </a>
            </div>        
          </div>
        </div>
      </div>
      {% endfor %}
    </div>
   </div> 
  <!-- End of Display ToDoro List Component -->

{% endblock %}